import AsyncStorage from "@react-native-async-storage/async-storage";
import { getApiBaseUrl } from "@/constants/oauth";
import {
  clearUserInfo,
  getSessionToken,
  getUserInfo,
  removeSessionToken,
  setUserInfo,
  type User,
} from "@/lib/_core/auth";
import { Platform } from "react-native";
import React, { createContext, useContext, useEffect, useState } from "react";

export type UserRole = "customer" | "driver" | null;

interface AuthContextType {
  /** A signed-in identity supplied by the server; never generated by the client. */
  userId: string | null;
  /** A post-login UI preference. It is not an authorization claim. */
  userRole: UserRole;
  isAuthenticated: boolean;
  isLoading: boolean;
  completeOAuthLogin: (user: User) => Promise<void>;
  logout: () => Promise<void>;
  setUserRole: (role: Exclude<UserRole, null>) => Promise<void>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);
const USER_ROLE_KEY = "userRole";

function getApiUrl(path: string): string | null {
  const baseUrl = getApiBaseUrl();
  return baseUrl ? `${baseUrl}${path}` : null;
}

function asUser(value: unknown): User | null {
  if (!value || typeof value !== "object") return null;
  const candidate = value as Partial<User>;
  if (typeof candidate.id !== "number" || typeof candidate.openId !== "string") return null;

  return {
    id: candidate.id,
    openId: candidate.openId,
    name: candidate.name ?? null,
    email: candidate.email ?? null,
    loginMethod: candidate.loginMethod ?? null,
    lastSignedIn: candidate.lastSignedIn ? new Date(candidate.lastSignedIn) : new Date(),
  };
}

export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [userRole, setUserRoleState] = useState<UserRole>(null);
  const [userId, setUserId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  const clearLocalSession = async () => {
    await Promise.all([
      AsyncStorage.removeItem(USER_ROLE_KEY),
      removeSessionToken(),
      clearUserInfo(),
    ]);
    setUserRoleState(null);
    setUserId(null);
  };

  useEffect(() => {
    const restoreServerSession = async () => {
      try {
        const apiUrl = getApiUrl("/api/auth/me");
        if (!apiUrl) return;

        const token = await getSessionToken();
        if (Platform.OS !== "web" && !token) return;

        const response = await fetch(apiUrl, {
          credentials: "include",
          headers: token ? { Authorization: `Bearer ${token}` } : undefined,
        });
        if (!response.ok) {
          await clearLocalSession();
          return;
        }

        const payload = (await response.json()) as { user?: unknown };
        const user = asUser(payload.user);
        if (!user) {
          await clearLocalSession();
          return;
        }

        await setUserInfo(user);
        const storedRole = await AsyncStorage.getItem(USER_ROLE_KEY);
        setUserId(user.openId);
        setUserRoleState(storedRole === "customer" || storedRole === "driver" ? storedRole : null);
      } catch (error) {
        console.error("[Auth] Failed to restore the server session", error);
        await clearLocalSession();
      } finally {
        setIsLoading(false);
      }
    };

    void restoreServerSession();
  }, []);

  const completeOAuthLogin = async (user: User) => {
    await setUserInfo(user);
    setUserId(user.openId);
    setUserRoleState(null);
    await AsyncStorage.removeItem(USER_ROLE_KEY);
  };

  const logout = async () => {
    const apiUrl = getApiUrl("/api/auth/logout");
    const token = await getSessionToken();

    try {
      if (apiUrl) {
        await fetch(apiUrl, {
          method: "POST",
          credentials: "include",
          headers: token ? { Authorization: `Bearer ${token}` } : undefined,
        });
      }
    } catch (error) {
      console.warn("[Auth] Server logout could not be completed", error);
    } finally {
      await clearLocalSession();
    }
  };

  const setUserRole = async (role: Exclude<UserRole, null>) => {
    if (!userId) {
      throw new Error("A server-authenticated session is required before choosing an app experience.");
    }

    await AsyncStorage.setItem(USER_ROLE_KEY, role);
    setUserRoleState(role);
  };

  return (
    <AuthContext.Provider
      value={{
        userRole,
        userId,
        isAuthenticated: userId !== null,
        isLoading,
        completeOAuthLogin,
        logout,
        setUserRole,
      }}
    >
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error("useAuth must be used within an AuthProvider");
  }
  return context;
}
